#! /usr/bin/env sh
make MXE_TARGETS='x86_64-w64-mingw32.shared' MXE_PLUGIN_DIRS=plugins/meson-wrapper -j3 JOBS=4 meson-wrapper cc
make MXE_TARGETS='x86_64-w64-mingw32.static' MXE_PLUGIN_DIRS=plugins/meson-wrapper -j3 JOBS=4 meson-wrapper cc
